apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: log
  labels:
    app: elasticsearch

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: elasticsearch
  volumeMode: Filesystem
  volumeName: elasticsearch-pv
  storageClassName: aws-sc
