apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticseach-sc
provisioner: ebs.csi.aws.com
parameters: 
  type: gp3
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - ap-southeast-1b

