apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-configmap
  namespace: log
data:
  kibana.yml: |
        server.name: kibana
        server.host: "0"
        elasticsearch.hosts: [ "http://elasticsearch:9200" ]
        elasticsearch.username: "kibana"
        elasticsearch.password: "uk8xxHFAz5khzyIk1pzv"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: log 
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: swapnil2000/kibana-logtrail:6.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
        env:
          - name: ELASTICSEARCH_URL
            value: elasticsearch.log.svc.cluster.local.:9200
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: config-data
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
      volumes:
      - name: config-data
        configMap:
          name: kibana-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: log
  labels:
    app: kibana
spec:
  #type: ClusterIP
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30000
  sessionAffinity: None
  selector:
    app: kibana

