kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-pv
  labels: 
    app: elasticsearch
    topology.kubernetes.io/region: ap-southeast-1
    topology.kubernetes.io/zone: ap-southeast-1b
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "vol-0a56bf71cd6684b31"
    fsType: ext4
  storageClassName: aws-sc
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - ap-southeast-1b
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - ap-southeast-1

